### ISSUE TITLE
Webscraping no longer allowed in HA

### ISSUE THREAD

**Issue by Bearfaced** [pschmitt/python-liveboxplaytv#98]
Hello, I know this is a big ask but in Home Assistant version 0.106 the Livebox Play TV integration was removed because it used web scraping (I assume to get the channel information). Would it be possible to create an updated version that just allowed status and control of the box?

I realize you have probably lots of better things to be doing with your time but it's worth asking!

Cheers,
Justin

**Comment by pschmitt** [comment]
Hi,

it never hurts to ask. Unfortunately I do not own a livebox anymore so I won't be working on this. Sorry!

**Comment by Bearfaced** [comment]
OK thanks! It was worth a try :) Have a great day!
